### ISSUE TITLE
ASX

### ISSUE THREAD

**Issue by jeracoo** [oscjaimes/rand-stock#5]
Consumer Non_durables always encounters error.
Public Utilities always encounters an error.

In regards to all Exchanges
I would add a sector called ALL to search all shares on that exchange, makes it more random, people love randomness.

**Comment by oscjaimes** [comment]
Thanks for the feedback, Matthew.
The sector names between the CSV files were not standardized, so I edited them manually, which clearly has some issues.

I will definitely add the 'ALL' sector for all stock symbols on exchanges.

Thanks for submitting this issue
